### ISSUE TITLE
Add job offer

### ISSUE THREAD

**Issue by jludvice** [pv207/bpm-diagrams#1]
![add job offer](https://cloud.githubusercontent.com/assets/8707241/15298316/fd3a2416-1b9e-11e6-83e4-2e4da5b57dee.png)

**Comment by jludvice** [comment]
@kytkaky
- part-time employees - "Inform Team Leader" tohle by myslim znamenalo, ze vsichni part-time zamestnanci uvidi "dostupny ukol" - jakmile si ho nekdo "vezme" tak ostatnim zmizi z nabidky.

Netusim jak na to namapovat "broadcast" - muze se ozvat 1..vsichni zamestnanci ze maji zajem.  
Nebo chceme uvazovat situaci "prvni vyhrava a ostatni maji smulu" ?

**Comment by kytkaky** [comment]
@jludvice aktuálně je to namodelované tak, že máš "job offer" pro každé místo "zvlášt" tzn 1 diagram = 1 místo -> v tom případě který part-time se ozve první a bude ohodnocený jako vhodný ten bere místo. aneb po tasku "informa abou decision and why" by neměl následovat END ale šipka zpátky do "Interested" gateway nebo k recruitmentu "offer to part-time"?

**Comment by jludvice** [comment]
Kdyz jeden zamestnanec zaklikne ze ma zajem a ukaze se jako nevhodny tak ta nabidka jde okamzite public, ze?

Co kdyz na to pujdem jinak - offer to part time employees bude odesilat e-mail na nejaky interni firemni mailing list a pak bud nejaky part-time employee klikne ze ma zajem a nebo ta "cekaci" aktivita po tydnu (treba?) timeoutuje a jde to na public job offer?

**Comment by kytkaky** [comment]
jj to je dobrej napad, jdu to upravit a uploadnu to

**Comment by kytkaky** [comment]
can we close this issue?

**Comment by kytkaky** [comment]
upravený timer
![add job offer](https://cloud.githubusercontent.com/assets/16515343/15329807/528df9ae-1c5a-11e6-9700-23caab41228c.png)

**Comment by jludvice** [comment]
Vypada to dobre, zaviram :)

**Comment by kytkaky** [comment]
jak jsi psal pepo udělala jsem z get offer a inform TL jeden task Apply for job na kterém je timer, plus ten cyklus jsem pořešila tak, že na assessment of part-time employee je standartní loop s poznámkou. plus jsem si četla "warningy od signavia" a u public job offer (když je to send message task) musí být kam ta zpráva putuje, takže přidán blackbox public
![add job offer](https://cloud.githubusercontent.com/assets/16515343/15334399/4c59efca-1c6e-11e6-89b1-410b0d67d066.png)

**Comment by kytkaky** [comment]
tak nakonec jsem "message" task před apply for job vrátila - aby bylo jasné že když recruitment odklikne že je to nabídka pro part-time, že part-timisti dostanou mail že je nabídka.... a jelikož to je message taks, tak se process okamžitě přesune na task apply for job. tam je timer....  uploadnuté v repository.
