### ISSUE TITLE
Closure course - implementation

### ISSUE THREAD

**Issue by kytkaky** [pv207/bpm-diagrams#11]
vybraný, snad jednoduchý, proces pro implementaci

**Comment by jludvice** [comment]
![project1 closurecourse](https://cloud.githubusercontent.com/assets/8707241/15633230/80a91f0c-25a7-11e6-8082-3bbe31231896.png)

**Comment by jludvice** [comment]
blog ohledne multi instance subprocesech http://mswiderski.blogspot.cz/2015/01/multiinstance-characteristic-example.html

**Comment by jludvice** [comment]
ten timeout sem prehodil na Recieve feedback task - tam mi prijde logictejsi - ten send je vicemene service task ktery je hotovy hned

**Comment by jludvice** [comment]
muzu roli "Lecturer" prepsat na "employee" stejne jako v #8 @kytkaky ?

**Comment by kytkaky** [comment]
Roli klidně přepiš a s tem timer jsem měla přehozenej ze špatného důvodu, takže taky OK

**Comment by jludvice** [comment]
Role potrebne v business centrale: `employee`  a `supervisor`

**Comment by jludvice** [comment]
recieve task jsem zmenil na signal event - neumim v business centrale v rozumnem usili prijimat zpravu - ma to klikatko jen na send signal...

![closure](https://cloud.githubusercontent.com/assets/8707241/15634200/6bbe300c-25be-11e6-967b-4c2787da83e7.png)

btw na to evaluation se mi podaril drop-down s moznostmi 
![select](https://cloud.githubusercontent.com/assets/8707241/15634228/e14d1400-25be-11e6-95c1-a2cd8aed2b40.png)

zbyva jeste dodelat formulare pro ty posledni user tasky po cousrse evaluation

**Comment by kytkaky** [comment]
drop-down je super vypchytávka, jen dotaz - budem davat do dokumentace tenhle jBPM diagram nebo ze signavia?  Pokud ze signavia mam to taky předělat na "signal event" ? nebo tam to nechat jako receive message - mam ho namodelovany i tam (import z jBPM)

**Comment by kytkaky** [comment]
plus tedka dodělávám ještě dokumentaci k tomuhle procesu a napada mě jestli by tam neměl byt nějakej data object - kam se zaznamenají ty změny kurzu? ale nechci ci to komplikovat

**Comment by jludvice** [comment]
ty automatizovane bych dal z jBPM - snad to nevypada nejak spatne a kdyztak se muzou jeste poladit aby to vypadalo lepe

data object - v tom jBPM jsem ho nenasel, to by se asi muselo udelat v signaviu :(

**Comment by kytkaky** [comment]
ale ty to stejně někam budeš ukladat ty změny ne? takže to hodim do signavia a přihodim do toho modelu ten "data object" ?

**Comment by jludvice** [comment]
konkretne v tomhle procesu to mas jako human task - remove course from offer - tedy nekomu bude svitit task ze ma v jinem systemu neco udelat.

Kdyby se to melo delat automatizovane, tak to bude nejaky service task / rest task...

Takhle se to snad obejde bez toho data objectu

**Comment by kytkaky** [comment]
slo mi spíš o task "Make changes in course" ale to bude fungovat stejným stylem takže už v tom mam jasno a nepotřebuju data object ;) Děkuji za kooperaci

**Comment by jludvice** [comment]
Snad finalni podoba tohoto procesu - smazal jsem na konci jeden XOR - za tim improve suggestions

![closurecourse](https://cloud.githubusercontent.com/assets/8707241/15670272/df5193e4-2724-11e6-8a87-0e0a16c9ded7.png)

potrebne role (uzivatel musi mit alespon roli `user` aby se mohl prihlasit do business centraly)
- employee
- supervisor

zaroven v tom procesu je vlastni WorkItem a Script Task / MVEL / na generovani reportu

**Comment by jludvice** [comment]
yahooo multiple instance subprocess jede

![closuresource](https://cloud.githubusercontent.com/assets/8707241/15681965/b3aa231e-275b-11e6-9b7f-31cfd042bcec.png)

ten signal ceka na 
- nazev `feedback`
- data - cokoliv
