### ISSUE TITLE
jBPM process registrace

### ISSUE THREAD

**Issue by jludvice** [pv207/bpm-diagrams#2]
navrh procesu

![registration-v2](https://cloud.githubusercontent.com/assets/8707241/15332720/0a3e0f06-1c67-11e6-937e-0ee5028d3904.png)

**Comment by jludvice** [comment]
prvni iterace - bez swimlanes
![jbpm-project registration](https://cloud.githubusercontent.com/assets/8707241/15335274/f09629b6-1c71-11e6-8783-db8859bc8cac.png)

**Comment by jludvice** [comment]
pridane swimlany

![jbpm-project registration 1](https://cloud.githubusercontent.com/assets/8707241/15420481/32d01254-1e6d-11e6-8a9b-0ee3e1c41660.png)

**Comment by jludvice** [comment]
pridana rest sluzba https://github.com/eduqick/jbpm-project/tree/master/rest-services pro dohledavani "approver" - id uzivatele ktery bude schvalovat firemni ucty

```
curl "http://localhost:8080/rest-services/rest/approver?email=somebody@redhat.com" -v
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /rest-services/rest/approver?email=somebody@redhat.com HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Sat, 21 May 2016 13:00:37 GMT
< 
* Connection #0 to host localhost left intact
{"manager":"jane","email":"somebody@redhat.com"}
```

**Comment by jludvice** [comment]
zdrojaky rest work item https://github.com/droolsjbpm/jbpm/blob/master/jbpm-workitems/src/main/java/org/jbpm/process/workitem/rest/RESTWorkItemHandler.java

Problem s 2 gatewayemi za sebou
![jbpm-project registration 2](https://cloud.githubusercontent.com/assets/8707241/15449219/c2f88194-1f77-11e6-93d6-1afc31dc1aef.png)

`IllegalArgumentException: Unknown gateway direction: Unspecified`
![sample gateway](https://cloud.githubusercontent.com/assets/8707241/15449222/e7b96610-1f77-11e6-9e31-2648ac3688ff.png)
[stdout.txt](https://github.com/eduqick/bpm-diagrams/files/275912/stdout.txt)

**Comment by kytkaky** [comment]
tak mě napadlo, jestli tam není problém v tom že ta druhá gateway ma jen jeden vystupní směr- ona tam vlastně ta druhý gateway být nemusí protože jen "chytá" všechny cesty aby šly do následujícího tásku jednou cestou.... nebo se mýlím?

**Comment by jludvice** [comment]
Tak zatim jsme tady (ten oranzovej) 
![jbpm-project registration 1](https://cloud.githubusercontent.com/assets/8707241/15453077/0467a198-2007-11e6-9786-cc135ac4d25c.png)

Zbyva
- naucit se posilat mejly
- vyresit deserializaci json -> objekt (nebo predelat rest service aby vracela jen ten string co chci - osklive reseni :)
- priradit ten "confirm request" primo uzivateli podle toho co vrati rest
- trochu si pohrat s formulari aby byly hezke
- service task na ulozeni uzivatele do databaze

**Comment by jludvice** [comment]
FakeSMTP ?  https://nilhcem.github.io/FakeSMTP/

Email WorkItem definition - use mvel

``` java
new org.jbpm.process.workitem.email.EmailWorkItemHandler("localhost", "1025", "me@localhost.cz", "password")
```

commit fix eduqick/jbpm-project@baa4ea4af8bcbcd8767e02116220630bb7d21919

**Comment by jludvice** [comment]
fix upstream javadoc https://github.com/droolsjbpm/jbpm/pull/471

**Comment by jludvice** [comment]
@todo approver => External HR

**Comment by jludvice** [comment]
parse workitem? https://github.com/droolsjbpm/jbpm/blob/master/jbpm-workitems/src/main/java/org/jbpm/process/workitem/parser/ParserWorkItemHandler.java

Work item definition

```
  [
    "name" : "Parse",
    "parameters" : [
      "Input" : new ObjectDataType(),
      "Format" : new StringDataType(),
      "Type" : new StringDataType()
    ],
    "results" : [
       "Result" : new ObjectDataType()
    ],
    "displayName" : "Parse",
    "icon" : "defaultservicenodeicon.gif"
  ],
```

**Comment by jludvice** [comment]
https://issues.jboss.org/browse/RHBPMS-3992

**Comment by jludvice** [comment]
why does this log omit end of class name ???????
https://issues.jboss.org/browse/RHBPMS-3994

```
20:09:59,353 WARN  [org.jbpm.kie.services.impl.KModuleDeploymentService] (http-127.0.0.1:8080-5) Unexpected error while deploying unit cz.muni.fi.pv207.eduqick:jbpm-project:1.0: java.lang.RuntimeException: [Error: could not create constructor: null]
[Near : {... new cz.muni.fi.pv207.eduqick.jbpm_ ....}]
                 ^
[Line: 1, Column: 5]
```

**Comment by jludvice** [comment]
Myslim si ze tenhle proces je hotovy, prosim o kontrolu @karlosko @kytkaky 

![jbpm-project registration](https://cloud.githubusercontent.com/assets/8707241/15614582/ed31ec90-2439-11e6-82e0-b190af02e9ca.png)

oranzovy task je primo na jmeno - je potreba uzivatel 'jane' s roli,
na zbytek human tasku je potreba role `user`

Magicky human task "Select company" - kdyz se tam napise redhat (ignoruji se mala velka pismena  a mezery) tak to pujde dal a schvaleni se priradi 'jane', v opacnem pripade se to vraci na vyber spolecnosti s chybovou hlaskou

Ulozeni do databaze je jen skript, ktery vypise do logu

```
18:00:27,750 INFO  [stdout] (http-127.0.0.1:8080-7) Executing work item WorkItem 33 [name=Log, state=0, processInstanceId=5, parameters{Message=Manager [manager=jane, email=me@redhat.com], TaskName=Log}]
18:01:15,098 INFO  [stdout] (http-127.0.0.1:8080-11) storing user User [id=null, login=fff, name=jj, surname=pp, email=me@redhat.com, corporateAccount=true] into db

```

**Comment by jludvice** [comment]
Tady je link na zbuildene [rest-services.war](https://github.com/eduqick/bpm-diagrams/raw/master/deployments/rest-services.war).
Staci zkopirovat do `$BPMS_HOME/standalone/deployments/`

**Comment by karlosko** [comment]
este k tomu select company, ako ze sme to nakoniec uzavreli? ze to overuje nejaka osoba z tej danej firmy, ano? a pokial to ona overi tak sa povoli registracia uzivatelovi, ktory bude moct reprezntovat skupinu ludi, ano?

**Comment by jludvice** [comment]
Tohle jsme myslim uzavreli tak ze jsou to 2 ruzne veci
A) tento proces - jednotlivec se chce registrovat (if corporate then ho schvaluje osoba z B)
B) jiny / nebyl modelovany / proces - uzavreme smlouvu s partnerem a na zaklade de mu dame pristup do systemu, ktery mu umozni registrovat skupiny

Pamatuju si to spravne?

**Comment by kytkaky** [comment]
Pepo přesně tak, v podstatě ten člověk kterej bude zastupovat skupinu může být ten External HR kterej schvaluje tu registraci jednotlivce když korporate ;)

**Comment by karlosko** [comment]
ano ano uz som si spomenul :), prepacte... len som si to chcel ujasnit lebo to pojdem doupravit v popise tych procesov ktorych sa to tyka

**Comment by kytkaky** [comment]
Konečně otestované, dotestované, proklikány všechny možnosti a všecko OK. Dobrá práce Pepo, I think that you can close this issue ;)

**Comment by jludvice** [comment]
Yahoooo ! Diky @kytkaky
