### ISSUE TITLE
 Registration process - short survey

### ISSUE THREAD

**Issue by jludvice** [pv207/bpm-diagrams#3]
@karlosko presunuto z pv207/jbpm-project#2

Ako jeden z objectives som vybral upevnenie pozicie na trhu - respektive zvysenie podielu na trhu.
Dal som tam tri objectives - narast customerov ( xx% narast customerov), narast customerov zapisanych na kurz (xx% narast v pocte vyskolenych ludi) a ze urcitu cast nasich novych customerov budu tvorit byvali customeri konkurencie...
cize by bolo asi nutne bud pri registracii alebo pri jeho prvom zapise na kurz, vnutit zakaznikovi aby mi nejako dal info o tom ci uz v minulosti vyuzival sluzby inej firmy alebo nie...

ja by som to riesil tak, ze v procese zapisu kurzu, v momente ked uz bude vsetko na tej spravnej ceste k samotnemu zapisu uzivatela na kurz, tak este pred zapisom skontrolujem ze ci ide o prvy kurz uzivatela a ak ano tak mu podstrcim survey ze ci doteraz bol uz skoleny u inej firmy

poprosim vas o nazor

**Comment by kytkaky** [comment]
dobrý nápad na objectives, jen bych tento krok nedavala do registrace ale dala bych to jako "anketku po přihlášení uživatele do systému" až bude zaregistrovanej (vyplní jednou a vícekrát se anketa danému uživateli nezobrazí)- mě by to v registraci osobně asi docela prudilo a možná by tomohlo i od dokončení registrace odradit.

**Comment by karlosko** [comment]
no ja som to potom na koniec tej svojej spravy aj napisal, ze asi to bude najlepsie pridat po prihlaseni na prvy kurz... lebo ked mu to dam vyplnit hned po registracii, respektive po prvom prihlaseni do systemu, tak  vobec nie je iste, ze si u nas nejaky kurz vobec zapise

**Comment by kytkaky** [comment]
Omlouvám se uniklo mi to slovíčko na kurz a brala jsem to že "na dobré cestě i registraci jako takové", s tím zápisem na kurz je to dobré řešení.

**Comment by kytkaky** [comment]
@karlosko budem tohle ještě nějak řešit?

**Comment by karlosko** [comment]
nooo momentalne to navrhnute nie je, ani ten objective nejako nerozvyjam a metriky ku nemu nijako nerozvyjam - mam ho uvedeny, ale nie je pouzity u ziadneho procesu... mam to tam domodelovat?

**Comment by jludvice** [comment]
pokud jinak splnujem pozadavky tak bych nedelal veci navic :)

**Comment by karlosko** [comment]
aha teda vlastne som sa pomylil, mam u toho user registration indikatory - yearly increase in registrations, registration dropout percentage a percentage of customers from competition... mam mat tym padom v procese povinne aj namodelovat aktivity kde zbieram udaje pre tie indikatory? 
lebo napriklad zistovanie poctu registracii do samotneho procesu registracie nepatri ale viaze sa ku tomu... tak isto to percento customerov od konkurencie je sice uvedene u registracie ale realne keby sa to niekde malo merat tak by to bolo u zapisu na kurz... a dropout rate si pepo ty spominal ze je zaujmavy ukazatel, preto som to pridal... ze napriklad na zaklade toho mozeme vyvodit ze je nasa registracia prilis komplikovana, ale tiez neviem v ktorom bode procesu by sa to meralo... 
cize otazka znie, ze ci ked sa ukazatel viaze k nejakemu procesu, tak ci v tom procese musi byt presne definovane miesto alebo aktivita, kde zbieram udaje k vyhodnoteniu toho ukazatela

**Comment by jludvice** [comment]
Myslim si (neber me 100% vazne) ze tohle patri do  te kategirie BAM - business activity monitoring.
Business centrala ma na to modul, kde se daji podobne statistiky nastavit a automaticky sbirat.
Tusim ze to neni treba montovat nikam do procesu ale vezme se to ze "servisnich informaci" - kolik instanci procesu bylo spusteno, kolik jich skoncilo v jakem koncovem stavu - to by si mel ukladat bpm engin sam od sebe do svoji databaze.

**Comment by karlosko** [comment]
Jo, ono v podstate viem presne ze co maju tie indikatory dokazazovat a z coho tie udaje vzidu, keby sa ma na to pytali... takze povazujme toto asi za uzavrete pokial nikto nema vyhrady

**Comment by jludvice** [comment]
Nemam vyhrady. @kytkaky tu BAM nemame povinou ze ne?

**Comment by kytkaky** [comment]
Ja určitě výhrady nemám, podle mě mají být k procesu přerazené KPI/KRI které se ho týkají a nemusí v něm přímo figurovat, to by bylo potom zbytečně komplikované.
co se týče povinosti BAM si nejsem jistá :/ mrknu se ještě do manuálu

**Comment by kytkaky** [comment]
Dle manuálu je BAM povinný jen pro Bizzagi, takže my můžem uplně v klidu vypustit. Na základě toho zavírám ;)
