### ISSUE TITLE
Check process New Course Date Proposal Evaluation 

### ISSUE THREAD

**Issue by jludvice** [pv207/bpm-diagrams#4]
@karlosko presunuto z pv207/jbpm-project#1

skontrolovat ci dava zmysel to, ze modelujem aktivitu - "ciernu skrinku" kde ocakavam ze zareaguje niektory zo skolitelov, a za touto aktivitou rovno mam gateway vetviaci flow podla toho "ci request niektori zo Skolitelov potvrdil"

**Comment by kytkaky** [comment]
@karlosko prosím o uvedení konkrétního modelu (a ideálně připojit screen se zvýrazněním daných tásků), mam toho tedka fakt hafec a času málo :( Díky.

**Comment by karlosko** [comment]
![diahgram](https://cloud.githubusercontent.com/assets/19391086/15365029/f9b006d6-1d1e-11e6-9295-5c0ccf2d729e.png)

**Comment by jludvice** [comment]
nejsem si jisty jeslti rozumim domu diagramu -
event new course date proposal >> check for circumstance new course added >> enroll user ?

Jak muze byt otevrene prihlasovani kdyz nekdo teprv navrhuje novy termin?

**Comment by karlosko** [comment]
uzivatel sa chce prihlasit na kurz, otvori si "overview" kurzu ale nie je ziadny volny termin... zasle poziadavku / navrh na pridanie noveho terminu kurzu, to je start tohto procesu...
kedze ja ako spravca mozem vyhodnocovat viacero takychto poziadavok narazovo, tak je mozne ze tym ze vyhoviem predchadzajucej ziadosti tak rovno vyhoviem aj niektorej z dalsich, preto je tam ta kontrola - chceck for circumstance change (znamena ze sa mohli zmenit okolnosti, a to tak ze ja ako skolitel vyhodnocujuci poziadavky som uz pridal novy termin, alebo ho dokonca mohol pridat niekto iny, kym prislo na vyhodnotenie poziadavky)... 
ak sa okolnosti nezmenili a stale plati ze ziadny nie je dostupny termin kurzu, tak prejdem k samotnemu rieseniu situacie

**Comment by kytkaky** [comment]
já bych tam dala timer na task "Lecturer new date reaction - pokud žádný z unoccupied  školiterů nezareaguje do nějaké doby  tak bude pokračovat jakoby po větvi "no" z XOR gaty pokud zareaguje tak bude pokračovat po YES větvi. Stejně tak bych to řešila u toho tasku Lecturer course capacity increase reaction a ještě bych přidala typ tasku u těch reakcí na "Send message"  a asi bych trošku pozměnila názvy těch tasků kde se posílá request  protože mi to "send" tam přijde zavádějící jako by to mělo být pomocí mailu nebo tak něco .... spíš bych tam dala něco jako "notice"  nebo "ask" e.g  "Ask selected available lecturer" a "Ask for increase capacity to the course" 
celkově mi přijdou strašně dlouhé názvy těch tasků v procesu, nevím jestli to nebudou kritizovat

**Comment by kytkaky** [comment]
možná je zbytečné to všechno přejmenovávat, a možná to není ani uplně dobrý nápad v některých přápadech, pak by bylo ale vhodné zvětšit velikost toho rámečku pro daný task aby to vypadalo opticky upravěnejší a přehlednější

**Comment by karlosko** [comment]
Jitka mozes to prosim hodit na zoznam veci co v pondelok treba doriesit? teda tie timery sa mi pacia, ale to nazvoslovie mozme prediskutovat osobne... ja som aktivity obsirnejsie popisal pre lepsie pochopenie, lebo to flow procesu nie je na pohlad uplne jasne (pepa tomu diagramu tiez bez popisu neporozumel, neviem ci mu vobec stacilo moje kratke vysvetlenie :D )

**Comment by jludvice** [comment]
@karlosko vysvetleni ok, ale jen z toho diadramu se to odhadovalo tezko. Kdyz na to prijde tak nejake kratoucke "nalepky" s vysvetlenim se tam myslim daji pridat

**Comment by kytkaky** [comment]
na seznam přidané, myslím že když nad tím v pondělí na chvíli sednem ala bainstorming tak to dame do kupy ;)
