### ISSUE TITLE
request team response subprocess

### ISSUE THREAD

**Issue by jludvice** [pv207/bpm-diagrams#8]
poslad dotaz definovane skupine uzivatelu a pockat na prvni OK odpoved nebo timeout / NOK od vsech

**Comment by jludvice** [comment]
@karlosko @kytkaky  nebude tohle dostatecne reseni?

![gateway requestresponse 1](https://cloud.githubusercontent.com/assets/8707241/15476590/278b6416-2110-11e6-9487-5539f1626360.png)

Vsichni zamestnanci ten pozadavek uvidi mezi tasky, pokud nekdo z nich odpovi, OK,
pokud nikdo neodpovi tak to vytimeoutuje...

**Comment by jludvice** [comment]
nebo jeste takhle s reminder upozornenim
![out](https://cloud.githubusercontent.com/assets/8707241/15477333/430868d4-2114-11e6-9e0f-5172ac6300d3.png)

**Comment by jludvice** [comment]
https://issues.jboss.org/browse/RHBPMS-3979
workaround https://access.redhat.com/solutions/2252321

**Comment by jludvice** [comment]
hotovo, pro vyzkouseni je potreba role `boss` a `employee`

![response](https://cloud.githubusercontent.com/assets/8707241/15542227/236c7cea-2290-11e6-9b18-de3677b29c23.png)

@kytkaky @karlosko muzete to nekdo vyzkouset proklikat?

**Comment by karlosko** [comment]
@Pepo najskor taky detail, na formulari pre writeRequest je nad formom label " *What do you need to know?", neviem ci to je nejaka univerzalna hlaska, ale asi by bolo vhodne zmenit (napr "Send new request" ?)...

dalej:
-vytvoril som s boss-om request
-ked som to chcel claimnut s employeem (ktoremu som ako username neuvazene dal employee) tak mi napisalo "Unexpected error occurred: Organizational entity already exists with [UserImpl:'employee'] id, please check that there is no group and user with same id"
-ked som novy request claimol s novym employeem tak som vyplnil normalne odpoved, dal save a potom complete a pri complete mi vypisalo: "Unexpected error occurred: null", pri dalsom complete to uz odrazu preslo - task tomu employeeemu zmizol (rovnako aj dalsim eployeem), ale cakal som ze pride aj nejake potvrdenie bossovi a neprislo... 
-pri daslom requeste sa mi to vobec nepodarilo completnut, stale pisalo "Unexpected error occurred: null"

edit: poznamka - ziadnemu userovi som nepridaval email ani nic podobne, len meno a role

**Comment by jludvice** [comment]
done
